# git-cliff configuration for changelog generation
[changelog]
header = """
# Changelog\n
All notable changes to VellumForge2 will be documented in this file.\n
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first | trim }}\
    {% endfor %}
{% endfor %}\n
"""
trim = true

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
commit_parsers = [
    { message = "^[Ff]eat", group = "Features" },
    { message = "^[Ff]ix", group = "Bug Fixes" },
    { message = "^[Dd]oc", group = "Documentation" },
    { message = "^[Pp]erf", group = "Performance" },
    { message = "^[Rr]efactor", group = "Refactoring" },
    { message = "^[Ss]tyle", group = "Styling" },
    { message = "^[Tt]est", group = "Testing" },
    { message = "^[Cc]hore", group = "Miscellaneous" },
    { message = "^[Bb]uild", group = "Build" },
    { message = "^[Cc][Ii]", group = "CI/CD" },
    { message = ".*", group = "Other Changes" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9]*"
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
