# golangci-lint v2.x configuration
version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
